# Generated by Django 5.1.2 on 2024-11-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_precinct_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.TextField(),
        ),
    ]
