# Generated by Django 5.1.3 on 2024-11-25 17:55

import uuid
from django.db import migrations, models

def populate_slug_field(apps, schema_editor):
    Portfolio = apps.get_model('investment_tracker', 'Portfolio')
    for portfolio in Portfolio.objects.all():
        portfolio.slug = uuid.uuid4()
        portfolio.save()


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.RunPython(populate_slug_field),  # Add this line to populate slug values
    ]
