# Generated by Django 5.1.3 on 2024-12-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tracker', '0005_alter_purchasedasset_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='latest_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
