# Generated by Django 5.1.2 on 2024-10-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0006_profile_user_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_key',
        ),
    ]
